In [70]:
import os
import logging
from typing import List, Dict, Tuple
from collections import Counter

import freecad
import FreeCAD
import Import
import Part
import os, shutil, json, time
from pathlib import Path
import pandas as pd

In [30]:
# Konfiguration
project_path = Path(os.getcwd()).parent
path_to_Gears = project_path / 'data/3_primary/fabwave/Gears'
path_to_HeadlessScrews = project_path / 'data/3_primary/fabwave/HeadlessScrews'

In [31]:
gear_files = list(path_to_Gears.rglob("*.step"))
hs_files = list(path_to_HeadlessScrews.rglob("*.step"))

In [32]:
def get_volumes(step_files):
    volumes ={}
    for step_file in step_files:
        doc = FreeCAD.newDocument(f"{step_file}")
        try:
            Part.insert(step_file.as_posix(), doc.Name)
            shapes = [volume.Shape for volume in doc.Objects]

            
            fused_shape = shapes[0] 

            volumes[step_file] = fused_shape.Volume

        except Exception as e:
            print(f"ERROR: {step_file} -> {e}\n")

        FreeCAD.closeDocument(doc.Name)

    return volumes

In [33]:
gear_volumes = get_volumes(gear_files)
hs_volumes = get_volumes(hs_files)

## check if the values are unique

In [37]:
len(set(gear_volumes.values()))==len(gear_volumes.keys()), len(set(hs_volumes.values()))==len(hs_volumes.keys())

(True, True)

## check for numerical effects.
These could lead to identical parts which could not be observed by the above method

In [94]:
df_gears = pd.DataFrame.from_dict(gear_volumes, orient='index', columns=['volume']).sort_values('volume')
df_hs = pd.DataFrame.from_dict(hs_volumes, orient='index', columns=['volume']).sort_values('volume')

In [95]:
sorted_gear_volumes = list(gear_volumes.values())
sorted_gear_volumes.sort()

sorted_hs_volumes = list(hs_volumes.values())
sorted_hs_volumes.sort()

In [96]:
def get_rel_deviations(sorted_lst):
    rel_deviations = []
    # calc relative dev to the next part each
    for i in range(1,len(sorted_lst)):
        lower = sorted_lst[i-1]
        higher = sorted_lst[i]

        rel_deviation = (higher-lower)/higher

        rel_deviations.append(rel_deviation)
    
    return rel_deviations

In [97]:
gear_dev = get_rel_deviations(sorted_gear_volumes)
hs_dev = get_rel_deviations(sorted_hs_volumes)

In [98]:
df_gears['dev_to_previous']=[1]+gear_dev
df_hs['dev_to_previous']=[1]+hs_dev

In [112]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    display(df_gears) #.sort_values('dev_to_previous')

,volume,dev_to_previous
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/f612b549-b8d8-4049-9a9c-ec865cbd6038.step,123.809785,1.000000
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/daa35be6-2d63-4fb2-8807-fe29d5d65271.step,136.584158,0.093527
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/d58620cc-e091-4f0d-8b11-81de14ea1e00.step,152.162835,0.102382
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/fcee0a82-2afe-45fb-bc27-66bbb9657395.step,202.609786,0.248986
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/00154245-00d1-4ead-9c17-98f80254af1b.step,230.696994,0.121749
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/c31b9db4-8875-4062-bccc-036a5cee2509.step,245.811739,0.061489
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/c5b42dac-bc35-4185-8a32-2b0e608e99f9.step,415.235211,0.408018
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/e6cfa40b-d249-4edd-8c60-c66b59c9666d.step,427.138567,0.027868
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/2f09a416-430f-4786-b7ba-158dd80e00b4.step,500.820588,0.147123
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/0d2ec54a-9297-406e-a0d4-e3af3ba5f3ac.step,575.174801,0.129272
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/d337b42a-f1e2-46c6-a148-32a92b7aa770.step,754.982704,0.238162
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/d91102ac-c2c3-4212-bcef-8a5702491a1b.step,781.363145,0.033762
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/354aea81-cb0c-44f7-b3f0-1e273d55e84c.step,898.242010,0.130120
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/b356e702-e51d-43d8-bd4b-171c3589485b.step,983.343293,0.086543
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/fbe883db-80f4-43fe-81a1-ff8b0f521c0f.step,1042.439959,0.056691
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/20c67e6b-8e67-4ab7-9583-49c718439ef3.step,1071.796286,0.027390
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/6bfe4000-a9dd-4da8-9536-336eedc0104b.step,1111.618819,0.035824
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/04f83e73-e5eb-4f73-aad8-61332c4b3a4f.step,1227.148674,0.094145
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/ac0691e3-70a6-4953-a0cc-33e80fceec24.step,1272.523852,0.035658
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/eb2c7ba1-de06-423c-bb38-93e56be0f828.step,1618.805354,0.213912
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/ae13dd39-6d82-48cf-90f6-ea7e058589ee.step,1619.098033,0.000181
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/115967d6-6377-4096-a91e-74034eb211a8.step,1907.933807,0.151387
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/ed299090-30e9-4130-8528-953714735079.step,1922.622908,0.007640
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/facab8d7-b84f-40f1-8a4a-64c350f12d7b.step,1959.711063,0.018925
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/b9b53484-0469-4371-adbc-d290f8f863ab.step,2238.460560,0.124527
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/98305526-f888-4198-86fa-7c7dc4812509.step,2245.464155,0.003119
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/b9825c2b-bd00-44eb-ac6d-8828d3e79c0a.step,3315.487827,0.322735
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/6f24b5e8-1a68-4053-9322-94e6a8729004.step,4229.779579,0.216156
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/5f068f63-2839-40c7-91a4-525cf69a274c.step,4336.090073,0.024518
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/ed501f36-2809-4a97-b24d-dc3b0cb9ce33_EXTRACTED_Gears.step,4550.250114,0.047066
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/633659d3-735c-45e7-88cc-516fd62f2182.step,4564.449729,0.003111
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/2fd31074-e15c-4025-bb78-04111f646eff.step,4595.782645,0.006818
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/ee93948e-2476-41a9-add7-6b138f11976a.step,4641.095969,0.009763
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/43ebcedf-083e-4028-8f4e-e653a504fa6d.step,4733.406126,0.019502
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/38fb1039-f0b4-4b96-af8f-0ee1d411efa0.step,4768.595193,0.007379
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/ee11081e-ccc1-47c8-8ebb-f0f57acb80a1.step,5050.923667,0.055896
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/e9f0035f-5b36-4eec-9825-c8acbfb46e70.step,5590.934569,0.096587
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/f25cc170-6ab8-4b63-a7c7-22c0f6776ef3.step,8239.672279,0.321462
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/4c9628da-41f3-4c38-ab4f-903e8b37cf49.step,8272.882794,0.004014
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/6ce6793c-e998-482d-881a-07e8e75dc102.step,8345.402089,0.008690
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/cd72d805-fa51-42b9-a24a-9c38dd4becb0_EXTRACTED_Gears.step,8546.395232,0.023518
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/d64a568d-1183-4827-a050-39969c57ea85_EXTRACTED_Gears.step,11205.643129,0.237313
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/8e0c7d3a-3acb-4b5b-8ccb-cf3a64730ea2.step,11967.099448,0.063629
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/6bb0e8e1-cb36-446a-8066-06290cb9a8b0.step,12075.451875,0.008973
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/a30f2cfe-94ad-46ea-87a8-fbc084a6bd48.step,12473.214722,0.031889
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/2dd59a9c-18d2-4674-b895-372af1ed4eec.step,13809.224762,0.096748
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/5a3fb73a-4657-4602-8c18-2740a8e89503_EXTRACTED_Gears.step,15035.881177,0.081582
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/962fc3c5-d142-4165-8c18-08af579f1d3c.step,16173.508296,0.070339
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/e5d8755a-7a42-400f-aebe-e11ccf53b5c1.step,16791.886114,0.036826
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/e20e523a-87b2-48f3-9e83-809c50c1685e.step,18504.268197,0.092540
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/6a44f649-b6ed-4c33-bb82-f70db92fd51f.step,18940.293958,0.023021
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/6ba51ffa-d7b3-4aa0-9e92-ee1134fb3ae8.step,21623.571400,0.124090
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/5522c725-1675-48ac-ab8d-09726ab67455.step,22292.585043,0.030011
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/a55d0346-8df4-43eb-85e7-55d416d653ee_EXTRACTED_Gears.step,24151.909791,0.076985
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/ac40ed73-2949-4097-99a1-8669cdb23187.step,28271.634560,0.145719
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/fc9f4e47-5b86-4217-922d-1e227ed6527d.step,28353.530257,0.002888
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/07e2817c-49d3-4e8e-b180-7a2f64ed0a55.step,28424.927039,0.002512
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/4f0968b8-408c-47b5-9003-21de98ebacd3.step,28825.033041,0.013881
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/e09edb93-82e7-489c-a26f-7ad61e1deecf.step,31796.592151,0.093455
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/c61e5cfd-0c23-4df6-9f5b-0ab30833ab80_EXTRACTED_Gears.step,36929.328615,0.138988
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/86f85ac0-1a9f-40eb-852a-fd632104b2c1_EXTRACTED_Gears.step,39926.116419,0.075058
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/2fd14ccd-91fc-4fed-bc13-83bd307fa1fe.step,42456.912207,0.059609
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/b407bba3-8ffe-4867-8245-53f71d2a6123_EXTRACTED_Gears.step,42553.166118,0.002262
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/cb6feec4-5712-4aad-8f72-c224675f22d9.step,45139.712322,0.057301
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/823d56e1-8b29-47aa-ac90-de594cb087a2_EXTRACTED_Gears.step,61829.533054,0.269933
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/89be3834-3837-4e91-bf3a-9ffc20734221_EXTRACTED_Gears.step,65417.622585,0.054849
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/82b420f6-881f-4c4d-af01-308fea1ab835_EXTRACTED_Gears.step,74857.589004,0.126106
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/9c39b264-af32-444b-b798-fd0e15fac58a.step,93768.428857,0.201676
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/3e30775f-4c8b-4b31-9bf6-381cf4a16dd6.step,98394.628839,0.047017
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/b2b568f8-0f80-4de0-b21a-880203c9d90d.step,105891.437482,0.070797
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/0a90fdb5-bc78-476d-83f5-ec7c507b2bdd_EXTRACTED_Gears.step,119522.512171,0.114046
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/eb595c09-3938-45e3-b110-20e1e743b060.step,145442.917330,0.178217
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/5dcaeac3-122d-45c5-ba7c-54d07864b85d_EXTRACTED_Gears.step,166577.768364,0.126877
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/Gears/0089079a-643f-4ca0-bfd6-01e0bc251c2d_EXTRACTED_Gears.step,227013.970616,0.266222

No duplicates detected in gears

In [111]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    display(df_hs)

,volume,dev_to_previous
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/1a360df4-13aa-4ace-a598-31b7e4d13048.step,1.379987e-01,1.000000e+00
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/e066d85f-c02f-4fd1-bb17-c0005a0e7c52.step,2.019519e-01,3.166751e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/88a4545e-5a2f-4b98-83fa-b818e270f04c.step,2.671271e-01,2.439858e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/637c68ea-6f0b-4b44-859f-0ee39f8024ab.step,3.530836e-01,2.434453e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/0aa83360-0704-4b06-8b3b-2b7774b7de92.step,4.285772e-01,1.761493e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/83648588-8d19-4013-8913-bbf76f5f7c99.step,5.368671e-01,2.017070e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/0554c639-fb1f-456f-8786-5225853908ab.step,5.994310e-01,1.043722e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/257e04d0-c8f6-4425-b66c-ef247a992e36.step,8.861768e-01,3.235763e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/3a5e90e5-4a41-415b-87c2-73adc5895a46.step,1.041999e+00,1.495416e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/2504c4b5-860f-40ef-95c7-d719ebefd065.step,1.430131e+00,2.713962e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/1d418d19-c4e6-4091-9fe6-8a65788b82ed.step,1.513235e+00,5.491817e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/476be865-457d-44d1-bba9-0d5198fce64a.step,1.911620e+00,2.084015e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/06b6181b-c1c6-471f-9f80-26753793c9ee.step,2.356266e+00,1.887080e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/c2a1aed4-cd60-49de-b10c-9a5949858156.step,3.415427e+00,3.101110e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/305c2f06-a4e8-46ba-bb08-f2cf770592af.step,4.923569e+00,3.063106e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/efb1ca1f-e011-4112-b908-1301468edf98.step,5.688813e+00,1.345174e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/cee20d5d-252c-4b6e-bbe4-0728dd3ae66e.step,6.510032e+00,1.261467e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/b0a1e6d0-0aa5-4efc-80df-d0c35e8144d1.step,7.127770e+00,8.666631e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/f72ef494-5024-4689-8bad-dce9450d2b74.step,1.006387e+01,2.917463e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/fd1ee61c-597e-4a3b-a6c7-519af0e70515.step,1.117166e+01,9.916081e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/ed501f36-2809-4a97-b24d-dc3b0cb9ce33_EXTRACTED_HeadlessScrews.step,3.115208e+01,6.413834e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/cd72d805-fa51-42b9-a24a-9c38dd4becb0_EXTRACTED_HeadlessScrews.step,4.476041e+01,3.040259e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/d64a568d-1183-4827-a050-39969c57ea85_EXTRACTED_HeadlessScrews.step,4.476041e+01,1.049158e-07
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/5a3fb73a-4657-4602-8c18-2740a8e89503_EXTRACTED_HeadlessScrews.step,5.460116e+01,1.802297e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/a55d0346-8df4-43eb-85e7-55d416d653ee_EXTRACTED_HeadlessScrews.step,6.631361e+01,1.766222e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/3216036b-1eb0-4d4b-855c-c03220fc649c.step,7.246478e+01,8.488488e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/c61e5cfd-0c23-4df6-9f5b-0ab30833ab80_EXTRACTED_HeadlessScrews.step,7.991941e+01,9.327687e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/33637f69-5e05-4ac4-b8b7-95b595adb3ca.step,8.789546e+01,9.074472e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/86f85ac0-1a9f-40eb-852a-fd632104b2c1_EXTRACTED_HeadlessScrews.step,9.290615e+01,5.393279e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/89be3834-3837-4e91-bf3a-9ffc20734221_EXTRACTED_HeadlessScrews.step,9.291137e+01,5.624053e-05
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/f161c7d2-5878-4e01-a526-ff92f3bf0d0c.step,9.617011e+01,3.388513e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/823d56e1-8b29-47aa-ac90-de594cb087a2_EXTRACTED_HeadlessScrews.step,1.014812e+02,5.233569e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/b407bba3-8ffe-4867-8245-53f71d2a6123_EXTRACTED_HeadlessScrews.step,1.014812e+02,2.895414e-07
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/82b420f6-881f-4c4d-af01-308fea1ab835_EXTRACTED_HeadlessScrews.step,1.169588e+02,1.323333e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/be062bdd-608c-4686-a190-c1697f390d25.step,1.271973e+02,8.049312e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/0089079a-643f-4ca0-bfd6-01e0bc251c2d_EXTRACTED_HeadlessScrews.step,1.397884e+02,9.007301e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/5dcaeac3-122d-45c5-ba7c-54d07864b85d_EXTRACTED_HeadlessScrews.step,1.397885e+02,1.701242e-07
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/0a90fdb5-bc78-476d-83f5-ec7c507b2bdd_EXTRACTED_HeadlessScrews.step,1.397885e+02,6.513432e-08
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/cbb85ef5-41a1-4e6a-9133-fd4e33e7fc48.step,1.723226e+02,1.887977e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/29079206-8e61-46c7-a034-4f19930a7866.step,2.272345e+02,2.416532e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/68d49356-72be-42b7-b39e-9e95d4d7a269.step,2.957829e+02,2.317522e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/e410b6a7-84bb-43af-980c-918412d75f7e.step,3.626604e+02,1.844082e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/5eadaaab-337b-4e49-bda5-41f530e4519d.step,4.840152e+02,2.507252e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/af40e775-086b-44af-9d68-e423c53b606f.step,5.224457e+02,7.355868e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/34e5b66c-93c1-4ff0-ac0a-2447776650bc.step,7.380937e+02,2.921690e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/e0365b82-1005-495c-afe1-7bb60c03cf7d.step,9.429658e+02,2.172635e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/732ab969-5de5-4300-9b73-dac92593f79f.step,1.224311e+03,2.297989e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/db6a93a0-9d7b-437f-8eea-ab2e05f3d093.step,1.444408e+03,1.523784e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/b6054bd8-c164-4be8-89e9-5322a4ea6141.step,1.684545e+03,1.425531e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/cb606ba9-8651-4de2-a620-33fcd12f3740.step,2.005061e+03,1.598539e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/ef24bc37-fe85-43f1-889d-81c8d5d92471.step,2.956725e+03,3.218642e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/5f5342a4-7b99-4a26-80bc-f9995d6a7ddb.step,3.412814e+03,1.336400e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/39adf041-797e-4908-bd46-2f4d69a6057f.step,3.959641e+03,1.381001e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/3af90925-dac7-4aec-8318-57c2424f36a9.step,4.160663e+03,4.831490e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/5d660137-d430-49f7-bd9a-a5da1119baae.step,4.462843e+03,6.771031e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/0b7971f8-fab9-4464-9f1e-f83b6a73f741.step,1.194468e+04,6.263740e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/d8c1984f-c616-45b4-b0b7-86b40a15f204.step,1.504101e+04,2.058589e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/5f5fb053-2ccb-42ec-9b65-18ad2ce71f25.step,1.815863e+04,1.716883e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/1e584e0b-ef11-4976-a631-106d26283ef9.step,2.195728e+04,1.730017e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/748d4fcc-ee05-4ed5-9b8b-f435235c3e4b.step,2.382315e+04,7.832179e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/d88a0f7d-f272-4a53-86b4-a060dd239fe1.step,2.801852e+04,1.497356e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/1f53f1cd-e650-4b2a-92ea-810f511e2ff7.step,2.838828e+04,1.302499e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/e5f688d7-fb3f-40a0-91b6-eb913e6a31b6.step,3.025731e+04,6.177115e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/007f4f3c-120a-4f13-81d9-53ce55055cb7.step,3.464881e+04,1.267433e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/32c1e4e7-509b-40e8-a66a-3ae50f4bb5e5.step,4.003265e+04,1.344861e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/3d15561c-24ca-4fc0-81b7-70289c73188d.step,4.262266e+04,6.076611e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/c9787bdf-f85d-4d28-a453-fa5311e9f621.step,4.661781e+04,8.570009e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/15c829d0-c280-4568-b693-f1ab0867ab22.step,5.188748e+04,1.015595e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/86e2500d-eb32-4673-b70a-a3b6541fb9b9.step,5.543779e+04,6.404137e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/d3db2145-8fe2-4112-8d54-27bfdc4dfeef.step,6.146613e+04,9.807585e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/7a605ced-54a3-4532-9a18-1d30a6ba21c6.step,6.567787e+04,6.412714e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/ba022e42-0533-49cb-8c37-ed7bfc46c41a.step,7.162411e+04,8.302007e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/e08d1a32-87f8-4cd5-8f9b-fdd60fe30855.step,8.304965e+04,1.375748e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/19fc6284-bb9d-4009-bd89-3daa5f0d0dc7.step,9.214648e+04,9.872146e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/55d158de-09dd-4a26-986f-95dc5a94b404.step,9.432842e+04,2.313130e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/6ead5409-a75e-4c2d-8686-48fbc2ba53ed.step,1.093141e+05,1.370879e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/1d669c73-4c9f-4cf9-a294-1fe4fe516c0b.step,1.154090e+05,5.281126e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/d21e35a6-dfce-4ebc-8254-aedc2bd09d8d.step,1.200676e+05,3.880058e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/52730c55-81e8-4621-8835-d20cf6e5be0a.step,1.290781e+05,6.980616e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/a8398b0f-48b6-44fb-a967-14932bbc70b9.step,1.333127e+05,3.176433e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/4cb42106-b7f3-4645-ad4e-2dabd4de7f21.step,1.484946e+05,1.022386e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/f650030e-d8cc-44d1-985e-16584ff1b08b.step,1.522184e+05,2.446403e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/89224fee-8f69-42f2-8c02-26ea17211e40.step,1.639501e+05,7.155645e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/dd692b0c-f7d9-46e7-b191-9b0156d65876.step,1.728449e+05,5.146100e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/231d8118-eeb9-4564-b381-810ca3871e7d.step,1.731035e+05,1.493740e-03
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/95d7a688-25b6-40aa-91b2-8d27a3d35bd8.step,1.840503e+05,5.947734e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/551e804a-33bb-4ed0-9166-3d73e1e47d03.step,1.953335e+05,5.776373e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/1c570d18-4431-464e-a2ef-3a8879904fe9.step,2.128880e+05,8.245889e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/5f17f11d-ecae-4949-8878-ee783548ca22.step,2.189076e+05,2.749857e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/55f6efaf-7d5c-486b-aaf3-286396418ff9.step,2.438268e+05,1.022004e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/f73d3f51-c655-4312-a0e6-6bb8fcd8bfbb.step,2.507357e+05,2.755437e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/c0195c5a-0f27-44e4-8921-f8004720ccc6.step,2.768661e+05,9.437921e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/9d846ad6-e3d4-4203-b469-2d54ff27ae3d.step,2.776042e+05,2.658903e-03
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/e6890981-9bb0-4769-9878-e9c9f7f932fc.step,3.120067e+05,1.102619e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/84501dd8-f5ee-4a12-9a76-821879178c4e.step,3.492402e+05,1.066129e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/3e88ec8e-f96b-42fc-84d3-c881ffd84705.step,3.885826e+05,1.012460e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/267cf192-04bf-4fba-8d2c-70093bfa56e4.step,1.687499e+06,7.697287e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/7484c885-fc6a-4870-bd6b-b210f8c62359.step,1.867799e+06,9.653054e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/213c9f3e-39d1-400e-9269-1be1013769ae.step,2.057254e+06,9.209119e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/2d132486-f286-4033-a62c-50306a5760ff.step,2.255865e+06,8.804212e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/086ce156-eb90-44b8-a530-b4a101e5abbf.step,2.463632e+06,8.433377e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/36e609df-48d1-476c-a6e2-8cea1907d52a.step,2.492273e+06,1.149174e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/8c126441-8e41-440f-8557-15287e320928.step,2.704945e+06,7.862359e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/5c820a2b-4854-4e65-b2e3-fadcbbc4e906.step,3.141871e+06,1.390655e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/cbd9a7ff-1f84-4b9c-ba62-b6043191fa54.step,3.156431e+06,4.612682e-03
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/cc50e750-5852-4ea2-bef2-4599978ad4bd.step,3.639811e+06,1.328038e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/e5ffdade-6295-4bad-ace1-1ab077a5c68f.step,3.642770e+06,8.121172e-04
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/b636ff49-ec12-42ae-b967-2c32a4d386f3.step,4.163970e+06,1.251690e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/9fb536e1-8435-48be-b68a-3713565e3f3f.step,4.174376e+06,2.492880e-03
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/8b45c0a6-8ac3-409e-8965-b8d1b0b1e71c.step,4.720018e+06,1.156017e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/54a86ad6-5cec-47ec-920e-79a4d9a2f173.step,4.745570e+06,5.384503e-03
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/367fdce1-f50a-4f37-ac5d-c43279a62bad.step,5.353424e+06,1.135448e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/fde3b1a6-1cf1-4c4f-b08d-10f26aaad0a9.step,5.501893e+06,2.698508e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/9f04d41f-bc6d-42fe-b9ee-7d28b5f54103.step,6.075824e+06,9.446143e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/0f889853-1677-4460-b492-6583e7423b5c.step,6.150908e+06,1.220703e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/26380618-4ab0-498a-8102-0416a86f6a71.step,6.765914e+06,9.089769e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/de4bf9f9-3d2a-4370-863e-facf5db207f2.step,6.835933e+06,1.024278e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/52d8ac06-1f47-45be-a815-1045dd1c1f5a.step,7.493123e+06,8.770577e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/c8a9f63e-5249-4c84-bc39-8d1055eea05d.step,7.557130e+06,8.469705e-03
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/fe2e138a-90c9-4de1-b75d-f34bc1298361.step,8.257451e+06,8.481083e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/37019129-3b30-41c4-98a1-f489b783d4e4.step,8.314497e+06,6.860970e-03
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/c3f50d57-4f25-453b-b818-5c3368d6029a.step,9.332645e+06,1.090954e-01
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/d2c3f787-5612-4df9-9339-f24abaa5f14a.step,9.473541e+06,1.487255e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/4bc1ecc4-d8ba-4de6-a2cb-4c9b5765fd3e.step,9.898089e+06,4.289198e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/0d840443-0dd8-4083-9993-f5d11427d814.step,9.937493e+06,3.965100e-03
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/a710769f-1f4a-4e86-b297-663713633b27.step,1.000409e+07,6.656680e-03
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/62d3e238-77c1-4d3d-9bc6-499b8f159cda.step,1.058249e+07,5.465671e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/cb2ab701-1487-4b2f-b092-7a8453dd0e38.step,1.063242e+07,4.696116e-03
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/879df45e-c554-4118-ba7f-730ec5dae49a.step,1.069712e+07,6.048211e-03
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/9eead52a-b10e-4c71-a481-d9a7fcddb3b1.step,1.140256e+07,6.186691e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/e61de7c7-77a1-4269-8f2f-bec04a9093ef.step,1.184370e+07,3.724701e-02
/Users/mkruse/Documents/repos/clear-shape/data/3_primary/fabwave/HeadlessScrews/6769954e-1dcc-491e-a686-c207fcb19da7.step,1.229318e+07,3.656285e-02

In [117]:
duplicates_hs = df_hs[df_hs.dev_to_previous < 0.001]

detect 6 files which should be handled as duplicates

In [ ]:
with open(r"../reports/raw->primary/detected_duplicates.csv", 'w') as f:
    for file in list(duplicates_hs.index):
        f.write(f"{str(file)},duplicate\n")